version: '3.8'

services:
  streamlit:
    build: ./streamlit_app2
    container_name: streamlit_app2
    volumes:
      - ./streamlit_app2:/app    # ←ホストのコードをコンテナの/appにマウント
    expose:
      - 8501
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - streamlit
    networks:
      - webnet

networks:
  webnet:
